### ISSUE TITLE
how to set key for bonding.......?

### ISSUE THREAD

**Issue by iqbalpalemad** [NordicSemiconductor/nRF51-ble-peripheral-bond-handling#1]
hi

how can i set the key that is used for bonding.......?

**Comment by vidarbe** [comment]
Storing of long term key is handled by the softdevice and device manager when key exchange has been initiated by the GAP central ([MSC](http://infocenter.nordicsemi.com/topic/com.nordic.infocenter.s130.api.v2.0.1/group___b_l_e___g_a_p___p_e_r_i_p_h___l_e_g_a_c_y___m_s_c.html?cp=3_7_2_1_0_2_1_3_8_7)). Please use the forum (devzone.nordicsemi.com) for questions that are not specific for this example.
